const TASK_TYPE_TARGET = 'TARGET';
const TASK_TYPE_PREPARE = 'PREPARE';
const TASK_TYPE_START = 'START';
const TASK_TYPE_FETCH_STORIES = 'FETCH_STORIES';
const TASK_TYPE_TESTS = 'TESTS';
const TASK_TYPE_TEST = 'TEST';
const TASK_TYPE_STOP = 'STOP';

module.exports = {
  TASK_TYPE_TARGET,
  TASK_TYPE_PREPARE,
  TASK_TYPE_START,
  TASK_TYPE_FETCH_STORIES,
  TASK_TYPE_TESTS,
  TASK_TYPE_TEST,
  TASK_TYPE_STOP,
};
